import { type ColDef } from 'ag-grid-community'
import { BadgeRenderer } from '../components/cell-editors'
import {
  collabTypeOptions,
  contentCategoryOptions,
  countryOptions,
  followerTierOptions,
  influencerCategoryOptions,
  presentationStyleOptions,
  yesNoOptions,
  type Creator,
} from '../data/data'
import {
  baseCreatorColumn,
  comboColumn,
  countryColumn,
  dateColumn,
  moneyColumn,
  numberColumn,
  numberFormatter,
  percentFormatter,
  teamColumn,
} from './column-helpers'

export const videoColumns: ColDef<Creator>[] = [
  {
    field: 'videoPublishedDate',
    headerName: '视频发布日期',
    width: 140,
    pinned: 'left',
    ...dateColumn(),
  },
  teamColumn,
  countryColumn,
  {
    field: 'dateVideoPost',
    headerName: 'Date Video Post（填表日期）',
    width: 210,
    ...dateColumn(),
  },
  {
    field: 'series',
    headerName: 'Series系列',
    width: 130,
    enableRowGroup: true,
  },
  { field: 'sku', headerName: 'SKU', width: 120 },
  baseCreatorColumn,
  {
    field: 'bd',
    headerName: 'BD',
    width: 110,
    enableRowGroup: true,
    cellRenderer: BadgeRenderer,
    ...comboColumn(['Anna', 'Bella', 'Chris', 'David', 'Elena'], 'badge', true),
  },
  { field: 'videoLink', headerName: 'Video Link', minWidth: 220 },
  { field: 'videoEncoding', headerName: 'Video Encoding', width: 160 },
  {
    field: 'influencerCategory',
    headerName: 'Influencer Category',
    width: 180,
    enableRowGroup: true,
    cellRenderer: BadgeRenderer,
    ...comboColumn(influencerCategoryOptions, 'badge', true),
  },
  {
    field: 'presentationStyle',
    headerName: 'Presentation Style',
    width: 170,
    enableRowGroup: true,
    ...comboColumn(presentationStyleOptions, 'plain', true),
  },
  { field: 'videoContent', headerName: 'Video Content', width: 160 },
  { field: 'videoScript', headerName: 'Video Script', width: 160 },
  { field: 'tiktokIdLink', headerName: 'Tiktok ID（链接', minWidth: 220 },
  {
    field: 'country',
    headerName: 'Country',
    width: 120,
    enableRowGroup: true,
    ...comboColumn(countryOptions),
  },
  { field: 'videoCode', headerName: '视频code', width: 130 },
  {
    field: 'contentCategory',
    headerName: 'Content Category',
    width: 160,
    enableRowGroup: true,
    cellRenderer: BadgeRenderer,
    ...comboColumn(contentCategoryOptions, 'badge', true),
  },
  {
    field: 'cumulativeInteractions',
    headerName: '互动量（累计）',
    width: 150,
    ...numberColumn(),
  },
  {
    field: 'likes',
    headerName: '点赞数',
    width: 120,
    ...numberColumn(),
  },
  {
    field: 'comments',
    headerName: '评论数',
    width: 120,
    ...numberColumn(),
  },
  {
    field: 'shares',
    headerName: '分享数',
    width: 120,
    ...numberColumn(),
  },
  {
    field: 'productExposuresCumulative',
    headerName: '商品曝光次数（累计）',
    width: 190,
    ...numberColumn(),
  },
  {
    field: 'productClicks',
    headerName: '商品点击次数',
    width: 150,
    ...numberColumn(),
  },
  {
    field: 'interactionRate',
    headerName: '互动率',
    width: 120,
    type: 'rightAligned',
    cellEditor: 'agNumberCellEditor',
    cellEditorParams: { min: 0, max: 1, precision: 4, step: 0.0001 },
    valueFormatter: percentFormatter,
  },
  {
    field: 'collabType',
    headerName: 'Collab Type',
    width: 150,
    enableRowGroup: true,
    ...comboColumn(collabTypeOptions),
  },
  {
    field: 'hasSales',
    headerName: '是否出单',
    width: 120,
    enableRowGroup: true,
    cellRenderer: BadgeRenderer,
    ...comboColumn(yesNoOptions, 'badge'),
  },
  {
    field: 'dealPieces',
    headerName: '成交件数',
    width: 120,
    type: 'rightAligned',
    cellEditor: 'agNumberCellEditor',
    valueFormatter: numberFormatter,
  },
  {
    field: 'gmv',
    headerName: 'GMV（总）',
    width: 130,
    ...moneyColumn(),
  },
  {
    field: 'followerTier',
    headerName: 'Follower Tier',
    width: 150,
    enableRowGroup: true,
    ...comboColumn(followerTierOptions),
  },
  { field: 'scriptDirection', headerName: '脚本方向', width: 130 },
  { field: 'skuCopy', headerName: 'SKU副本', width: 130 },
  { field: 'tiktokIdCopy', headerName: 'Tiktok ID副本', width: 150 },
  { field: 'bdCopy', headerName: 'BD 副本', width: 120 },
  { field: 'collabTypeCopy', headerName: 'Collab Type副本', width: 160 },
]
